name = "Software & Beyond"
description = "A simple blog theme focused on writing powered by Bulma and Zola."
license = "MIT"
homepage = "https://github.com/RatanShreshtha/Software & Beyond"

min_version = "0.9.0"

demo = "https://Software & Beyond-theme.netlify.app/"

[extra]

[author]
name = "Ratan Kulshreshtha"
homepage = "https://ratanshreshtha.dev"
