on:
  push:
    branches:
      - master
name: Build and deploy on push
jobs:
  build:
    name:  emosenkis/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: emosenkis/zola-deploy-action
      uses: emosenkis/zola-deploy-action@master
      env:
        TOKEN: ${{ secrets.ZOLA }}
