on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.8941703fdb658bc01936bade55e497d3b2d5a038 }}
