on:
  push:
    branches:
      - master
name: Build and deploy on push
jobs:
  build:
    name:  yehia2amer/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yehia2amer/zola-deploy-action
      uses: yehia2amer/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        TOKEN: ${{ secrets.ZOLA }}
